<?php
/**
 * Function to automatically create a standard sitemap.xml
 * https://www.itsupportguides.com/knowledge-base/wordpress/wordpress-how-to-automatically-create-sitemap-xml-without-plugin/
 * https://blog.jallet.org/generer-un-fichier-sitemap-xml-sans-plugin-490.html
 * https://codex.wordpress.org/Filesystem_API
 * https://www.sitemaps.org/protocol.html
 * 
 * V3 hacer sitemap con custom feed
 * http://www.wpbeginner.com/wp-tutorials/how-to-create-custom-rss-feeds-in-wordpress/
 * https://codex.wordpress.org/Customizing_Feeds
 * https://codex.wordpress.org/WordPress_Feeds#Site_comment_feed
 * https://codex.wordpress.org/Rewrite_API/add_feed
 * https://codex.wordpress.org/Rewrite_API/add_rewrite_rule
 *
 * @package ekiline
 */

if( true !== get_theme_mod('ekiline_sitemap') ) return;

/* Agregar el feed: sitemap y aplicar regla de sobreescritura en url */
function ekiline_sitemap_init(){
	add_feed('sitemap', 'ekiline_sitemap');
}
add_action('init', 'ekiline_sitemap_init');

/* Filtrar el contenido // HTTP header for Content-type. */
function ekiline_sitemap_content_type( $content_type, $type ) {
	if ( 'sitemap' === $type ) {
		return feed_content_type( 'rss-http' );
	}
	return $content_type;
}
add_filter( 'feed_content_type', 'ekiline_sitemap_content_type', 10, 2 );

/* Dar formato al XML y mostrar: domain.com/?feed=sitemap o domain.com/feed/sitemap */
function ekiline_sitemap() {
	
	$sitemap = '' ;
	
	$sitemapLimit = get_theme_mod('ekiline_sitemaplimit');
	
	if ( $sitemapLimit == '0' || null ){
		$sitemapLimit = '1';
	} else if ($sitemapLimit >= '200'){
		$sitemapLimit = '200';
	}
	
	// Adjust timezone to follow XMl standard
	if( str_replace( '-', '', get_option( 'gmt_offset' ) ) < 10 ) {
		$timeZone = '-0' . str_replace( '-', '', get_option( 'gmt_offset' ) ) ;
	} else {
		$timeZone = get_option( 'gmt_offset' ) ;
	}
	
	if( strlen( $timeZone ) == 3 ) {
		$timeZone = $timeZone . ':00' ;
	}
	
	// Select posts and pages
	$arrayPosts = array( 'post','page' );
	if ( class_exists( 'WooCommerce' ) ) {
		$arrayPosts = array( 'post','page','product' );
	} 	

	$postsForSitemap = get_posts(array(
		//	'numberposts' => -1,
			'numberposts' => $sitemapLimit,
			'orderby' => 'modified',
			'post_type' => $arrayPosts,
			'order' => 'DESC'
	));
	
	// Sitemap header
	$sitemap .= '<?xml version="1.0" encoding="UTF-8"?>' . "\n";
	$sitemap .= '<?xml-stylesheet type="text/xsl" href="'.get_template_directory_uri() . '/css/sitemap.xsl"?>' . "\n";
	$sitemap .= '<!-- Generated by Ekiline SEO Wordpress Theme (ekiline.com) -->' . "\n";
	$sitemap .= '<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' . "\n";
	// Generate homepage xml set
	$sitemap .= "\t" . '<url>' . "\n" . 
				"\t\t" . '<loc>' . esc_url( home_url( '/' ) ) .'</loc>' . 
				"\n\t\t" . '<lastmod>' . date( "Y-m-d\TH:i:s", current_time( 'timestamp', 0 ) ) . $timeZone . '</lastmod>' . 
				"\n\t\t" . '<changefreq>daily</changefreq>' . 
				"\n\t\t" . '<priority>1.0</priority>' . 
				"\n\t" . '</url>' . "\n" ;

	// Generate entry for each post/page
	foreach( $postsForSitemap as $post ){
		setup_postdata( $post ) ;
		$postdate = explode( ' ', $post->post_modified ) ;
		
		//set priority by type of post
		$priority = '0.8';
		$pfreq = 'weekly';
		$ptype = explode( ' ', $post->post_type ) ;
		if ($ptype[0] == 'page'){ $priority = '0.5'; $pfreq = 'monthly'; }
		
		$sitemap .= "\t" . '<url>' . "\n" . 
					"\t\t" . '<loc>' . get_permalink($post->ID) . '</loc>' . 
					"\n\t\t" . '<lastmod>' . $postdate[0] . 'T' . $postdate[1] . $timeZone . '</lastmod>' . 
					"\n\t\t" . '<changefreq>' . $pfreq . '</changefreq>' . 
					"\n\t\t" . '<priority>' . $priority . '</priority>' . 
					"\n\t" . '</url>' . "\n" ;
	}

	// Sitemap closing tag
	$sitemap .= '</urlset>' ;
	
	echo $sitemap;

}
